### ISSUE TITLE
status light stay red even if connected

### ISSUE THREAD

**Issue by SuperNinja73** [bartbutenaers/node-red-contrib-onvif-nodes#12]
it remains red because it received an order which did not work . If I run a command that works ,  the status indicator stays red and does not refresh the new state "Connected" ok

**Comment by bartbutenaers** [comment]
Hi Chris,
Do you have an example flow to reproduce this?
Tried to inject an unknown command into a couple of Onvif nodes, but I cannot reproduce it:

![image](https://user-images.githubusercontent.com/14224149/95390285-6f2a8780-08f5-11eb-8acf-0b94a825cb13.png)

Bart

**Comment by SuperNinja73** [comment]
![image](https://user-images.githubusercontent.com/53425740/95458952-34673480-0973-11eb-9a84-df80c652cd9e.png)
I could not tell you what is the payload which puts the node in default.
On the other hand, on this example:
- if I ask for a function that works: "Get nodes" the status is green and I have an answer
- but as soon as I ask for a function that does not work for my camera: "Get configuration options" for example, the status is red failed.
- When I ask "Get nodes" again, I have an answer, but the status is still red, it does not go back to green.

**Comment by bartbutenaers** [comment]
Chris,
Indeed the status was not being reset after an error.  But the problem is that I should reset to the current status after x seconds, which might have been changed meanwhile (which makes it difficult to implement).  Moreover there was an [discussion ](https://discourse.nodered.org/t/pull-request-proposal-temporary-node-status/28081) some time ago ***temporary node statuses***, which unfortunately was a dead end for temporary node statuses.

So for both reasons, I now don't show the temporary nodes statuses anymore (i.e. it keeps being e.g. `connected`).  But instead I use `node.error` to make sure the errors ends up into the debug sidebar:

![image](https://user-images.githubusercontent.com/14224149/95511630-048e5000-09b8-11eb-8f6c-5ecd951e8dba.png)

Does this makes sense to you?

**Comment by bartbutenaers** [comment]
@SuperNinja73,
Is this ok for you?

**Comment by SuperNinja73** [comment]
> @SuperNinja73,
> Is this ok for you?

@bartbutenaers : yes  it's ok for me
